### ISSUE TITLE
Doesn't work on Safari / iPhone / iPad

### ISSUE THREAD

**Issue by ghost** [LikaloLLC/tourguide.js#24]
When I view the tour on my iPad or iPhone in Safari and in Chrome, all positioning is messed up. 

It doesn't matter if I do it in my app - or in the JS fiddle example on the main page, all highlighted elements are dead center, and the prompts appear in random locations. 

I wish I'd known this before adding it to every section of my app!
![123](https://user-images.githubusercontent.com/65848492/99394841-74f19080-28d7-11eb-8959-1c20ca422cb3.png)

**Comment by PhilippeTrounev** [comment]
@andeh38 can you please take a look into this bug
