### ISSUE TITLE
Don't hide overlay between 2 steps

### ISSUE THREAD

**Issue by michaelfr** [LikaloLLC/tourguide.js#25]
Hi,

Congrats for this project ! 

I integrate it on my product, but there is a tiny problem.

When we are jumping from step to step, unactive the overlay and active the overlay and it's like a blinking and it's a deceptive effet. 

Can you help me ?

Regards

Michael

**Comment by PhilippeTrounev** [comment]
@andeh38 can you please take a look into this bug

**Comment by andeh38** [comment]
Hi, if I understood your problem correctly adding this to your css file might solve it
 `.guided-tour-step.active .guided-tour-step-highlight {
  box-shadow: none !important; 
}` @michaelfr

**Comment by syAndyDev** [comment]
Hi @michaelfr ,
I have made pull request #27 for fixing this bug.
If I understood your problem correctly let me know.
