### ISSUE TITLE
Typo in demo

### ISSUE THREAD

**Issue by tacman** [LikaloLLC/tourguide.js#40]
**Describe the bug**

There's a typo in  the demo

**To Reproduce**

Go to the demo and go through the tour.  The last card says card 4

![image](https://user-images.githubusercontent.com/619585/108393302-7fc30680-71e1-11eb-937b-6f92aa46b30a.png)

**Expected behavior**
Should say card 2

**Comment by PhilippeTrounev** [comment]
@syJSdev can you please take a look and fix :)

**Comment by syAndyDev** [comment]
The above example will be replaced with the new examples. Look PR (#46)
So close it.
