### ISSUE TITLE
Add backward navigation

### ISSUE THREAD

**Issue by tacman** [LikaloLLC/tourguide.js#41]
**Describe the solution you'd like**

I'd like to be able to go backwards in the tour without clicking on the nav dots.

A left chevon, opposite the one on the right, to go back to the previous slide.

![image](https://user-images.githubusercontent.com/619585/108393666-de888000-71e1-11eb-95d8-4d3c00f57fa5.png)

**Comment by PhilippeTrounev** [comment]
@syJSdev hi Jain, can you please take a look at this.
