### ISSUE TITLE
Colors doesn't work

### ISSUE THREAD

**Issue by SimonLandeholm** [LikaloLLC/tourguide.js#54]
**Describe the bug**
According to the readme you should be able to set colors. But this feature seems to be unimplemented.

**To Reproduce**
1. create a new tourguide with `new Tourguide({colors: {bullet: '#000'}})`
2. the colors are unchanged

**Expected behavior**
bullet color should be black

**Desktop (please complete the following information):**
 - Browser chrome

**Additional context**
There's no mention of colors anywhere in the sourcecode downloaded from npm v0.3.0. Is this a build issue? I can see that it's implemented in the github source

**Comment by PhilippeTrounev** [comment]
Sorry for the delay. We've made some updates to the library and released 1.0. It has a color option explicitly specified in the docs. Can you take a look and let us know if this fixed the issue.
