### ISSUE TITLE
Support for Vuejs, Reactjs

### ISSUE THREAD

**Issue by duccanhole** [LikaloLLC/tourguide.js#68]
Hi, I want use this repo for Vuejs (or Reactjs). Do you support for this? If yes, please provide docs and demo.
Thanks you.

**Comment by PhilippeTrounev** [comment]
@Wesley-Nunes could we create some examples to share with the community.

**Comment by Wesley-Nunes** [comment]
Hi, @duccanhole.
You can look at some react examples here: [React examples](https://github.com/LikaloLLC/tourguide.js/tree/master/examples/example_reactjs).
