### ISSUE TITLE
Highlight styles not being applied

### ISSUE THREAD

**Issue by chrisj74** [LikaloLLC/tourguide.js#70]
**Describe the bug**
Set style for highlight not applying styles

**To Reproduce**
1. initiate new guide
2. Inspect he active highlight dom element `div.guided-tour-step.active > div.guided-tour-step-highlight`
3. The width, height, top and left style props are not set

**Expected behavior**
Highlight should be set to the target + padding

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser Chrome latest
 - Version 1.1.2

**Additional context**
Looking at the code seems as thought the values for the styles are being passed as numbers (without the 'px') assigning the style object without the unit of measurement does not work. This does work in 1.0.1, so seems a regression.

**Comment by PhilippeTrounev** [comment]
@Wesley-Nunes please take a look.

**Comment by Wesley-Nunes** [comment]
Okay, I'll look at it.

**Comment by PhilippeTrounev** [comment]
@chrisj74  we opened a PR today and its merged to master. I will update it on NPM today.

**Comment by ThornWalli** [comment]
@PhilippeTrounev Can it be that the publish on npm for `1.1.3` is still missing with the fix?

- https://github.com/LikaloLLC/tourguide.js/pull/71
  - PR hat Package version `1.1.3`
- https://www.npmjs.com/package/tourguidejs?activeTab=versions

**Comment by ryuuto** [comment]
It appears to me that the latest release available in NPM is `1.1.2`. When will the changes in version `1.1.3` be applied to the NPM repository?

**Comment by PhilippeTrounev** [comment]
Wow, talk about missing the mark on this one. I pushed the latest fix. Sorry everyone.
